version: '3.9'

services:
  django:
    build: 
      context: ./server/folketsserver
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  react:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
