# Generated by Django 4.1 on 2024-05-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folkets_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingcommercial',
            name='amount_of_donations',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ongoingcommercial',
            name='current_donation_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ongoingcommercial',
            name='max_donation_amount',
            field=models.IntegerField(null=True),
        ),
    ]
