# Generated by Django 4.1 on 2024-05-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folkets_app', '0002_ongoingcommercial_amount_of_donations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingcommercial',
            name='status',
            field=models.CharField(default='active', max_length=100),
        ),
    ]
